version: '3'

services:
  client:
    container_name: clientApp_container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/clientApp
      - /clientApp/node_modules
    env_file:
      - ./client/.env.local  
    depends_on:
      - server
    #tty: true

  server:
    container_name: serverApp_container
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/serverApp/src 
    env_file:
      - ./server/.env       
    depends_on:
      - redis
    #tty: true

  redis:
    image: redis
    ports:
      - "6379:6379"
